spring:
  data:
    mongodb:
      username: riad
      password: riad
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090